apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-gdb
spec:
  selector:
    matchLabels:
      app: hello-world-gdb
  template:
    metadata:
      labels:
        app: hello-world-gdb
    spec:
      containers:
      - image:  shlomoweiss/hello-world-gdb:1.0.0.0
        name: hello-world-gdb
        securityContext:
         capabilities:
           add: ["SYS_PTRACE"]

---

apiVersion: v1
kind: Service
metadata:
  name: hello-world-gdb
spec:
  type: ClusterIP
  ports:
    - name: "hello-world-gdb"
      port: 5000
  selector:
    app: hello-world-gdb




